### PR TITLE
Fixed ItemGroup typings to allow for non-array value prop

### PR DESCRIPTION
**Pull request by marekdedic**
Probably a leftover from #49

### CODE REVIEW

**Comment by marekdedic** [comment]
Eh, the original PR wasn't even merged...

Anyway, as per [the docs](https://github.com/TheComputerM/svelte-materialify/blob/master/packages/docs/src/examples/ListItemGroup/mandatory.svelte), you should be able to do this. And it actually works in my code. So it's probably just the typings haven't been updated?

**Comment by Florian-Schoenherr** [comment]
@marekdedic might be only number or array for ItemGroup, this one is correct.

**Comment by Florian-Schoenherr** [comment]
@marekdedic might be only number or array for `ItemGroup`, the docs you link to are `ListItemGroup`.

**Comment by Florian-Schoenherr** [comment]
`ItemGroup` seems to handle all the possible inputs, so we _could_ merge this, but I think you want to use `ListItemGroup`?

**Comment by marekdedic** [comment]
Yeah, but the typings for `ListItemGroup` inherit from `ItemGroup` - so should they be separated?

**Comment by Florian-Schoenherr** [comment]
You're right, they do. Let's keep it like that.

**Comment by marekdedic** [comment]
I can change the message and force push, no problem. I'm a bit lost though - is this the solution you want to go for?

**Comment by Florian-Schoenherr** [comment]
Yup. I just didn't know about the inheritance.

**Comment by marekdedic** [comment]
Yeah, well, I've kind of given up on smui ever supporting TS... :/

**Pull request merged**
