### PR TITLE
feat(NumberField): numeric input component

### PR DESCRIPTION
**Pull request by gristow**

### CODE REVIEW

**Comment by gristow** [comment]
This component is meant to provide the kind of numeric binding that Svelte provides on `<input type="number" />` and preserve all relevant options from `TextField`.

And so, its styles are entirely shared with `TextField`. I opted not to create new NumberField.scss and _variable.scss files -- which would have been near duplicates of those for TextField because of this. But, this means quite a few "text-field" classes are applied, and it makes the code structure less clear, since these files don't reside in the same directory as `NumberField`.

I'd appreciate feedback on the structure: Does it makes more sense to create new .scss files for this component? Should these be extracted to a higher level and shared? If we do that, should we rename "text-field" to something else where it occurs in styles?

Thanks!

**Comment by TheComputerM** [comment]
This will generate duplicate styles, and is this a bug with svelte as we are setting the type to 'number' and it is still returning string?

**Comment by gristow** [comment]
> is this a bug with svelte as we are setting the type to 'number' and it is still returning string?

Not a bug with Svelte, per Rich Harris's [answer on StackOverflow](https://stackoverflow.com/a/57393751/1731473), the `type` prop must be static with two-way binding because the code Svelte generates is different depending on the kind of input.

As a result, even when we set `<TextField type="number" />` the value will be a string. [See playground example](https://svelte.dev/repl/faf8538354d54f27959e6af47200fb91?version=3.35.0).

> This will generate duplicate styles

Yes, I agree -- which is why I wonder about abstracting the styles to a higher level?

Alternately, one sort of super-component could be set to observe the "type" property and swap out html `<input />` elements accordingly via an `{#if type='number'}...{/if}` block?

**Comment by TheComputerM** [comment]
I am thinking of coming up with a new format using [svelte:fragments](https://github.com/sveltejs/svelte/pull/4556) such as:

```html
<InputField>
  <svelte:fragment slot="label">
    Label Text
   </svelte:fragment>
  <input type='text' />
</Input Field>
```

This would allow us to add textarea, numberic field and text field in one component and not too much extra css.

**Comment by gristow** [comment]
In that approach, would `<InputField />` replace `<TextField />`? Or, would `<TextField />`, `<NumberField />` `<TextAreaField />`, etc..., use `<InputField />` as a child component?

(I'd vote for the second option, especially since the accepted props on the different kinds of inputs are different. This would let us define those separately for each input type for the purposes of clear documentation, and also for typescript users.)

I'm not familiar with the `<svelte:fragment />` syntax, or I'd offer to do this. (Frankly, I'm only two weeks in to working with Svelte, but I'm loving it.)

In any case, let me know how you want me to proceed with regards to this PR. If you want to create an `<InputField />` I'm happy to rewrite `<NumberField />` to use it.

**Comment by TheComputerM** [comment]
The only problem with that would be forwarding props.  I'll see what I can do to solve this, you can also post here if you have come up with a solution.

**Comment by gwelr** [comment]
A solution here would be great (and we need it as we are engaged in a project where several fields are numeric fields only). For now we are using `<input type=number>` with custom css applied, but this is far from being optimal. I look forward learning how you plan to solve this. And keep up the good work :-)

**Comment by gristow** [comment]
Since it seems we agree this approach is not the right one, even if we're not decided on a solution, I'm closing and opening issue #224 as a place to discuss a possible solution.

**Pull request closed without merging**
