### PR TITLE
Docs fixes

### PR DESCRIPTION
**Pull request by Graphmaxer**
2 little bugs that I noticed when I developed the new Tooltip component 😄

### CODE REVIEW

**Comment by TheComputerM** [comment]
I don't see a problem with the alert. MDSveX does not parse markdown inside components.

**Comment by Graphmaxer** [comment]
There is a space after the last paragraph in this alert for example (on the tooltip page). This fix is based on https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/components/Alert.vue

image

**Comment by TheComputerM** [comment]
Wierd:
image

**Comment by Graphmaxer** [comment]
In this page ? https://svelte-materialify.vercel.app/components/tooltips/

**Comment by Graphmaxer** [comment]
I'm on Chrome and I can clearly see the 16px margin on bottom 
image

**Comment by TheComputerM** [comment]
No, sorry, false alarm.

**Comment by TheComputerM** [comment]
Thanks!

**Pull request merged**
