### PR TITLE
fix: sliderUi library imported incorrectly for SPA and SSR #171

### LINKED ISSUE #171: Not working with Svelte Kit (Vite)
I am not sure if there is some special configuration to do with https://github.com/sveltejs/kit but this is the error I am getting when trying to use a simple Button component.

```
<Button> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
```

### PR DESCRIPTION
**Pull request by V-ed**
Closes #171

Based on these two resources, works in my Vite SPA application :

- https://github.com/TheComputerM/svelte-materialify/issues/171#issuecomment-802991037
- https://kit.svelte.dev/docs#troubleshooting-server-side-rendering

### CODE REVIEW

**Comment by Florian-Schoenherr** [comment]
[Slider docs](https://svelte-materialify-git-fork-v-ed-patch-1-thecomputerm.vercel.app/components/sliders/) throw an error, because of [this line](https://github.com/TheComputerM/svelte-materialify/blob/11b8f7faac6251a84a0edeeb973d3076a0c18233/packages/svelte-materialify/src/components/Slider/Slider.svelte#L99).
should be:
`if (slider && value !== localValue) slider.set(value, false);`

**Comment by V-ed** [comment]
> Edit, completely forgot: Thank you! That's the right approach :)
> Can you try the below suggestion?
> 
> [Slider docs](https://svelte-materialify-git-fork-v-ed-patch-1-thecomputerm.vercel.app/components/sliders/) throw an error, because of [this line](https://github.com/TheComputerM/svelte-materialify/blob/11b8f7faac6251a84a0edeeb973d3076a0c18233/packages/svelte-materialify/src/components/Slider/Slider.svelte#L99).
> should probably be:
> `if (slider && value !== localValue) slider.set(value, false);`

Thanks :)

Good catch, I tested through the vercel deploy (ain't gonna lie, I didn't go through the contribution guides... sorry ") ) but somehow missed the fact that you couldn't go on another page after loading the spinner doc, that's kinda problematic haha

Should be good now, I applied the fix you mentionned, let's see if the docs on the new vercel deploy will work or not!

**Comment by Florian-Schoenherr** [comment]
Interesting.
Could you change the commit messages to conventional commits and force push?
It's also okay if you don't, just remember for next time :)

**Comment by V-ed** [comment]
@Florian-Schoenherr Just read the contribution guide and saw that it is indicated to use conventional commits, my bad :/

In this case though, I don't remember the default Github behavior but isn't `squashing and merging` taking the PR title for the commit message? I could change that one instead (beside, my 3 commits should really be 1, especially the trailing spaces one), if the current one isn't descriptive enough (it could be `fix: sliderUi library imported incorrectly for SPA and SSR #171`)

**Comment by V-ed** [comment]
Awesome that squashing takes the PR title, good to know for the future :)

Thanks for the quick responses and have a great day!

**Comment by dit7ya** [comment]
Great that it has been solved now! Has this fix been pushed to the `npm` package yet?

**Comment by V-ed** [comment]
Hey @Florian-Schoenherr, I saw that you made a tag on GitHub containing, amongst others, this PR, but the package hasn't been updated on NPM - did you forget or is there something else preventing the update from going live? I kinda don't want to commit to my branches in my own repo since I know this package will break my builds...

**Comment by Florian-Schoenherr** [comment]
@TheComputerM is releasing to NPM, he will do that soon (there was some kind of mistake)

**Comment by V-ed** [comment]
> @TheComputerM is releasing to NPM, he will do that soon (there was some kind of mistake)

Gotcha, didn't intend to put pressure btw ;)

Thanks for the info!

**Pull request merged**
