### PR TITLE
force update the items when they are changed

### PR DESCRIPTION
**Pull request by romanown**
it is enough to set a simple check condition that in fact does not change anything, but forces the component to update the data.

### CODE REVIEW

**Comment by Florian-Schoenherr** [comment]
Now I get it, it should react when `items` changes..

**Comment by Florian-Schoenherr** [comment]
`items && format(value)` seems to work as well

**Comment by romanown** [comment]
ok. i do it

**Comment by romanown** [comment]
I made the change you suggested

**Comment by romanown** [comment]
many thanks to you for this. now I can safely continue to use this library in my work. I will try to be useful to this library.

**Pull request merged**
