### PR TITLE
fix: set Appbar z-index

### LINKED ISSUE #36: select dropdown appear behind other controls.
In  this REPL
https://svelte.dev/repl/aaec9bbff21540aab79d507b692d3f36?version=3.29.0

The select dropdown list appear behind a button.

### PR DESCRIPTION
**Pull request by Florian-Schoenherr**
Fixes #36

### CODE REVIEW

**Comment by Florian-Schoenherr** [comment]
@TheComputerM should the navbar z-indexes always be below the appbar z-indexes? I would personally remove z-index: 6. Or how exactly is this meant to work? Or I could increase appbar z-index even more.
image

**Comment by TheComputerM** [comment]
I think we should have a (better) default value and let users customize it.

**Comment by Florian-Schoenherr** [comment]
> I think we should have a (better) default value and let users customize it.

Ok, for now I'm gonna make the nav drawer z-index 4 on the base and allow for specifying via a prop. (.fixed then only applies position: fixed)

**Comment by Florian-Schoenherr** [comment]
API generation now adds a `\n` to all the json files, so it doesn't count as a commitable change.
(It does show as a change, but that's the same as before. When you `git add` the API json files, nothing other than real changes will show up)

**Pull request merged**
