### PR TITLE
Update Api generation to use type definitions

### PR DESCRIPTION
**Pull request by Graphmaxer**
Hello, I implemented an extractor to get the description of the type definitions files. I used this [file](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker) as inspiration. Currently its work pretty well for the description of props. There is possible improvements for type detection and for future slots/events when [this](https://github.com/sveltejs/rfcs/pull/37) get approved.

### CODE REVIEW

**Comment by TheComputerM** [comment]
Thanks, this is good for the time being, will implement a parser based on [typedoc](https://typedoc.org/) later.

**Comment by TheComputerM** [comment]
If you are working on something major (like this), it is better to open an issue first so anyone can give their suggestions.

**Comment by Graphmaxer** [comment]
Ok no problem, I will open a new issue for discussion 👍

**Comment by Graphmaxer** [comment]
I close this PR because a typedoc implementation will be better.

**Comment by TheComputerM** [comment]
Why did you close this, I was telling for next time, this is fine.

**Pull request closed without merging**
