### PR TITLE
Add Tooltip

### PR DESCRIPTION
**Pull request by Graphmaxer**
Hello, I have started working with a Svelte/Sapper project and I'm using your svelte-materialify which is really good 👍 . I have already used Vue with Vuetify in the past. So I added a new Tooltip component based on the Vuetify source code. I changed a bit compared to the original Vuetify one, I have a named slot `tip` instead of `activator`. Feel free to suggest anything on this PR, I have plenty of time. BTW I will probably try to contribute more to this repository 😉 .

You can check my project here : https://gitlab.com/partyboard/webapp and https://partyboard-webapp.herokuapp.com

### CODE REVIEW

**Comment by TheComputerM** [comment]
Thanks, incredible work :clap:, and a nice project you got there (I will add a showcase section to svelte materialify something the future).

Just a few things:
- export Tooltip from the main [index.js](https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/src/index.js)
- remove comments above props from the svelte file add create a `.d.ts` file at `@types` folder for Tooltip, eg:
  - [Button.svelte](https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/src/components/Button/Button.svelte)
  - [Button.d.ts](https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/%40types/Button.d.ts)

**Comment by Graphmaxer** [comment]
Done 😄 ! But with the `.d.ts` file, the api-generator does not find the description of the props.

**Comment by TheComputerM** [comment]
Thanks, I am planning to rewrite the api generator to also include types.

**Comment by Graphmaxer** [comment]
I will open a new PR, there is a bug due to a eslint fix.

**Pull request merged**
