### PR TITLE
fix(select): selecting the same item (#54)

### PR DESCRIPTION
**Pull request by rodgco**
Fix a bug with Select as described on issues #54 and #62. Solution is to set a default value for prop ```mandatory={true}``` at the Select component.

### CODE REVIEW

**Comment by rodgco** [comment]
Just created a [REPL](https://svelte.dev/repl/a9e91a9f68f14ae3a372bf0c9f1df506?version=3.29.7) to showcase the problem

**Comment by TheComputerM** [comment]
This is not an actual fix for the problem, just a workaround.

**Comment by rodgco** [comment]
I agree this is a workaround, and the final solution is probably to eliminate the "mandatory" prop of select, and enforce ```mandatory={true}``` down the component chain.

If you take a look at how other select components (specially native) behave you must always select something, once you select something you cannot choose nothing (unless it is an option = an item).

**Comment by Florian-Schoenherr** [comment]
Before we just delete the prop, yes mandatory should be defaut true, but the problem arises from internals trying to do value[0] somewhere, which should probably just check for null. Maybe it should be eliminated..

**Comment by rodgco** [comment]
I agree, it needs further investigation to come to a real solution. Unfortunately how context and stores are being used in this particular implementation (ItemGroup) is beyond my ability to comprehend it, so there is not much I can help here.

**Comment by TheComputerM** [comment]
This has been fixed.

**Pull request closed without merging**
