### PR TITLE
added fix for on:change support for select component

### LINKED ISSUE #131: Missing on:change event on Select component
It would be very helpful to have an onChange-event available on the select component.

### PR DESCRIPTION
**Pull request by tonprince**
Closes #131

### CODE REVIEW

**Comment by Florian-Schoenherr** [comment]
Have you tried https://github.com/TheComputerM/svelte-materialify/issues/131#issuecomment-778586845 ?

**Comment by tonprince** [comment]
> Have you tried [#131 (comment)](https://github.com/TheComputerM/svelte-materialify/issues/131#issuecomment-778586845) ?

Yes, but without success.

**Comment by Florian-Schoenherr** [comment]
either `on:click={() => dispatch('change', { value: item.value }) }` but with proper indent, or, if it works well, just:
`$: dispatch('change', value)` in `<script>`. Could you test the second one?
Less LOC and binding `value` and emitting `change` should react the same way anyways.

**Comment by Florian-Schoenherr** [comment]
@tboulis if you want, you can make a new PR with commits in conventional commit format. Like I said, the reactive dispatch would be easiest 👍

**Comment by kickermeister** [comment]
The reactive dispatch approach (`$: dispatch('change', value)` in `<script>`) worked for me. See https://github.com/kickermeister/svelte-materialify/commit/de87983a7b646ad461e1b999e74cc4879d80e2d4 

Would you like me to make a new PR as suggested?

**Comment by Florian-Schoenherr** [comment]
@kickermeister please go ahead 😄

**Pull request closed without merging**
